# Customise this file, documentation can be found here:
# https://github.com/krausefx/fastlane#customise-the-fastfile

# Change the syntax highlighting to Ruby

# All lines starting with a # are ignored when running `fastlane`

before_all do
  cocoapods
  increment_build_number ENV["BUILD_NUMBER"]
end

lane :test do
  snapshot
end

lane :alpha do

  cert
  sigh :adhoc

  xctest(
      destination: "name=iPhone 5s,OS=8.1",
      report_formats: [ "html", "junit" ],
      report_path: "./build-dir/reports", # will use XCODE_BUILD_PATH/reports, if not provided
      report_screenshots: true
    )

  ipa({
    workspace: "Wikipedia.xcworkspace",
    configuration: "Debug",
    scheme: "Wikipedia",
  })

  # xctool

#  hockey({
#  api_token: 'c881c19fd8d0401682c4640b7948ef5e',
#  notes: "Changelog",
#  notify: 0
})
  # deliver :testflight
end

lane :beta do
  sigh :adhoc
  deliver :testflight
end

lane :appstore do
  snapshot
  sigh
  deliver :skip_deploy, :force
  # frameit
end

after_all do |lane|
  # This block is called, only if the executed lane was successful
  # slack({
  #   message: "Successfully deployed new App Update for [App](http://link.com).",
  #   success: true,
  #   channel: 'development'
  # })
end


error do |lane, exception|
  # Something bad happened
end
