# Customise this file, documentation can be found here:
# https://github.com/krausefx/fastlane#customise-the-fastfile

# Change the syntax highlighting to Ruby

# All lines starting with a # are ignored when running `fastlane`

before_all do
  reset_git_repo :force
  ensure_git_status_clean
  cocoapods
  increment_build_number ENV["BUILD_NUMBER"]
end

lane :test do

  xctest(
    workspace: "Wikipedia.xcworkspace",
    scheme: "WikipediaAlpha",
    configuration: "Alpha",
    destination: "platform=iOS Simulator,name=iPhone 5s,OS=8.2",
    report_formats: [ "html", "junit" ],
  )

end

lane :alpha do

  cert

  sigh({
    adhoc: true,
    force: true,
    provisioning_name: "TF Beta Adhoc"
  })

  # xctest(
  #     workspace: "Wikipedia.xcworkspace",
  #     scheme: "WikipediaAlpha",
  #     configuration: "Alpha",
  #     destination: "platform=iOS Simulator,name=iPhone 5s,OS=8.2",
  #     report_formats: [ "html", "junit" ],
  #   )

  ipa({
    workspace: "Wikipedia.xcworkspace",
    configuration: "Alpha",
    scheme: "WikipediaAlpha",
    clean: nil, # this means 'Do Clean'. Clean project before building.
    archive: nil, # this means 'Do Archive'. Archive project after building.
    verbose: nil, # this means 'Do Verbose'.
  })


 #  hockey({
 #    api_token: 'c881c19fd8d0401682c4640b7948ef5e',
 #    notes: "Changelog",
 #    notify: 0
 # })

  deliver :testflight, :beta, :force
end

lane :beta do
  sigh :adhoc
  deliver :testflight
end

lane :appstore do
  snapshot
  sigh
  deliver :skip_deploy, :force
  # frameit
end

after_all do |lane|
  # This block is called, only if the executed lane was successful
  # slack({
  #   message: "Successfully deployed new App Update for [App](http://link.com).",
  #   success: true,
  #   channel: 'development'
  # })
end


error do |lane, exception|
  # Something bad happened
end
