# Customise this file, documentation can be found here:
# https://github.com/krausefx/fastlane#customise-the-fastfile
# vim: ft=ruby

# Since this file is eval'd, we need to add this file's directory to $LOAD_PATH
$:.unshift File.dirname(__FILE__)

require 'lib/utils.rb'

before_all do
  p ENV
end

lane :test do
  make 'lint'
  run_unit_tests
end

lane :alpha do
  ensure_git_status_clean

  run_unit_tests

  # Download the Certificate for signing
  cert

  # Create and/or download the right provisioning profile
  sigh({
    force: true,
    provisioning_name: 'TF Alpha',
    app_identifier: 'org.wikimedia.wikipedia.tfalpha',
  })

  # Create the app in iTunes Connect if needed
  produce({
    produce_username: ENV['APPLE_USER_NAME'],
    produce_app_identifier: 'org.wikimedia.wikipedia.tfalpha',
    produce_app_identifier_suffix: '', #work around for: https://github.com/KrauseFx/produce/issues/27
    produce_app_name: 'Wikipedia Alpha',
    produce_language: 'English',
    produce_version: ENV['VERSION_NUMBER'],
    produce_sku: '01985',
  })

  # Set variables for building and distributing
  ENV['IPA_BUILD_SCHEME'] = 'Wikipedia Alpha'
  ENV['IPA_BUILD_CONFIG'] = 'Alpha'
  ENV['APP_APPLE_ID'] = '981253550'

  deploy_testflight_build

end

lane :beta do
  ensure_git_status_clean

  run_unit_tests

  # Download the Certificate for signing
  cert

  # Create and/or download the right provisioning profile
  sigh({
    force: true,
    provisioning_name: 'TF Beta',
    app_identifier: 'org.wikimedia.wikipedia.tfbeta',
  })

  # Create the app in iTunes Connect if needed
  produce({
    produce_username: ENV['APPLE_USER_NAME'],
    produce_app_identifier: 'org.wikimedia.wikipedia.tfbeta',
    produce_app_identifier_suffix: '', #work around for: https://github.com/KrauseFx/produce/issues/27
    produce_app_name: 'Wikipedia Beta',
    produce_language: 'English',
    produce_version: ENV['VERSION_NUMBER'],
    produce_sku: '01984',
  })

  # Set variables for building and distributing
  ENV['IPA_BUILD_SCHEME'] = 'Wikipedia Beta'
  ENV['IPA_BUILD_CONFIG'] = 'Beta'
  ENV['APP_APPLE_ID'] = '974795031'

  deploy_testflight_build

end

lane :appstore do
  ensure_git_status_clean

  run_unit_tests

  # Download the Certificate for signing
  cert

  # Create and/or download the right provisioning profile
  sigh({
    provisioning_name: 'org.wikimedia.wikipedia AppStore',
    app_identifier: 'org.wikimedia.wikipedia',
  })

  # Create the app in iTunes Connect if needed
  produce({
    produce_username: ENV['APPLE_USER_NAME'],
    produce_app_identifier: 'org.wikimedia.wikipedia',
    produce_app_identifier_suffix: '', #work around for: https://github.com/KrauseFx/produce/issues/27
    produce_app_name: 'Wikipedia Mobile',
    produce_language: 'English',
    produce_version: ENV['VERSION_NUMBER'],
    produce_sku: '01982',
  })

  # Set variables for building and distributing
  ENV['IPA_BUILD_SCHEME'] = 'Wikipedia'
  ENV['IPA_BUILD_CONFIG'] = 'Release'
  ENV['APP_APPLE_ID'] = '324715238'

  deploy_appstore_build

end

lane :experimental do
  # Download the Certificate for signing
  cert

  # Create and/or download the right provisioning profile
  sigh({
    force: true,
    provisioning_name: 'TF Experimental',
    app_identifier: 'org.wikimedia.wikipedia.tfexperiment',
  })

  # Create the app in iTunes Connect if needed
  produce({
    produce_username: ENV['APPLE_USER_NAME'],
    produce_app_identifier: 'org.wikimedia.wikipedia.tfexperiment',
    produce_app_identifier_suffix: '', #work around for: https://github.com/KrauseFx/produce/issues/27
    produce_app_name: 'Wikipedia Experimental',
    produce_language: 'English',
    produce_version: '5.0',
    produce_sku: '01986',
  })

  # Set variables for building and distributing
  ENV['IPA_BUILD_SCHEME'] = 'Wikipedia Experimental'
  ENV['IPA_BUILD_CONFIG'] = 'Experimental'
  ENV['APP_APPLE_ID'] = '986242662'

  deploy_testflight_build

end

# after_all do |lane|
# end

# error do |lane, exception|
# end
